# Generated by Django 5.2.7 on 2025-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTecnoFelipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Esta activo?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Razon social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimaCompra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Última Compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Es destacado?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='urlImagen',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Imagen'),
        ),
    ]
